package c_like.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c_like.Absyn.EInt p, A arg);
    public R visit(c_like.Absyn.EDouble p, A arg);
    public R visit(c_like.Absyn.EString p, A arg);
    public R visit(c_like.Absyn.ETrue p, A arg);
    public R visit(c_like.Absyn.EFalse p, A arg);
    public R visit(c_like.Absyn.EId p, A arg);
    public R visit(c_like.Absyn.ECall p, A arg);
    public R visit(c_like.Absyn.EPIncr p, A arg);
    public R visit(c_like.Absyn.EPDecr p, A arg);
    public R visit(c_like.Absyn.EIncr p, A arg);
    public R visit(c_like.Absyn.EDecr p, A arg);
    public R visit(c_like.Absyn.ENeg p, A arg);
    public R visit(c_like.Absyn.EMul p, A arg);
    public R visit(c_like.Absyn.EDiv p, A arg);
    public R visit(c_like.Absyn.EAdd p, A arg);
    public R visit(c_like.Absyn.ESub p, A arg);
    public R visit(c_like.Absyn.ELt p, A arg);
    public R visit(c_like.Absyn.EGt p, A arg);
    public R visit(c_like.Absyn.ELEq p, A arg);
    public R visit(c_like.Absyn.EGEq p, A arg);
    public R visit(c_like.Absyn.EEq p, A arg);
    public R visit(c_like.Absyn.ENEq p, A arg);
    public R visit(c_like.Absyn.EAnd p, A arg);
    public R visit(c_like.Absyn.EOr p, A arg);
    public R visit(c_like.Absyn.EAss p, A arg);

  }

}
