package c_like.Absyn; // Java Package generated by the BNF Converter.

public class Pdefs  extends Program {
  public final ListDef listdef_;
  public Pdefs(ListDef p1) { listdef_ = p1; }

  public <R,A> R accept(c_like.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof c_like.Absyn.Pdefs) {
      c_like.Absyn.Pdefs x = (c_like.Absyn.Pdefs)o;
      return this.listdef_.equals(x.listdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdef_.hashCode();
  }


}
