package c_like.Absyn; // Java Package generated by the BNF Converter.

public abstract class Program implements java.io.Serializable {
  public abstract <R,A> R accept(Program.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c_like.Absyn.Pdefs p, A arg);

  }

}
