package Clike.Absyn; // Java Package generated by the BNF Converter.

public class Tstring  extends Type {
  public Tstring() { }

  public <R,A> R accept(Clike.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Clike.Absyn.Tstring) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
