
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Clike;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\003\000\002\003" +
    "\002\000\002\003\004\000\002\004\012\000\002\005\002" +
    "\000\002\005\003\000\002\005\005\000\002\006\002\000" +
    "\002\006\004\000\002\007\004\000\002\010\004\000\002" +
    "\010\005\000\002\010\007\000\002\010\007\000\002\010" +
    "\005\000\002\010\007\000\002\010\005\000\002\010\011" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\003\000\002\011\003\000\002\011\003\000\002" +
    "\011\006\000\002\011\005\000\002\012\004\000\002\012" +
    "\004\000\002\012\004\000\002\012\003\000\002\013\004" +
    "\000\002\013\004\000\002\013\003\000\002\014\005\000" +
    "\002\014\005\000\002\014\003\000\002\015\005\000\002" +
    "\015\005\000\002\015\003\000\002\016\005\000\002\016" +
    "\005\000\002\016\005\000\002\016\005\000\002\016\003" +
    "\000\002\017\005\000\002\017\005\000\002\017\003\000" +
    "\002\020\005\000\002\020\003\000\002\021\005\000\002" +
    "\021\003\000\002\022\005\000\002\022\003\000\002\023" +
    "\003\000\002\024\003\000\002\025\003\000\002\026\003" +
    "\000\002\027\003\000\002\030\003\000\002\031\002\000" +
    "\002\031\003\000\002\031\005\000\002\032\003\000\002" +
    "\032\003\000\002\032\003\000\002\032\003\000\002\032" +
    "\003\000\002\033\002\000\002\033\003\000\002\033\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\016\002\uffff\031\uffff\032\uffff\036\uffff\040" +
    "\uffff\042\uffff\001\002\000\004\002\172\001\002\000\016" +
    "\002\000\031\007\032\006\036\014\040\013\042\012\001" +
    "\002\000\004\047\uffc1\001\002\000\004\047\uffc2\001\002" +
    "\000\004\047\015\001\002\000\016\002\ufffe\031\ufffe\032" +
    "\ufffe\036\ufffe\040\ufffe\042\ufffe\001\002\000\004\047\uffbe" +
    "\001\002\000\004\047\uffbf\001\002\000\004\047\uffc0\001" +
    "\002\000\004\004\016\001\002\000\016\005\ufffc\031\007" +
    "\032\006\036\014\040\013\042\012\001\002\000\004\047" +
    "\171\001\002\000\006\005\ufffb\010\167\001\002\000\004" +
    "\005\022\001\002\000\004\006\023\001\002\000\052\004" +
    "\ufff9\006\ufff9\007\ufff9\013\ufff9\014\ufff9\015\ufff9\031\ufff9" +
    "\032\ufff9\034\ufff9\035\ufff9\036\ufff9\037\ufff9\040\ufff9\041" +
    "\ufff9\042\ufff9\043\ufff9\044\ufff9\045\ufff9\046\ufff9\047\ufff9" +
    "\001\002\000\052\004\033\006\032\007\031\013\027\014" +
    "\026\015\025\031\007\032\006\034\055\035\054\036\014" +
    "\037\053\040\013\041\052\042\012\043\050\044\041\045" +
    "\034\046\062\047\030\001\002\000\022\004\033\013\027" +
    "\034\055\041\052\044\041\045\034\046\062\047\030\001" +
    "\002\000\022\004\033\013\027\034\055\041\052\044\041" +
    "\045\034\046\062\047\030\001\002\000\022\004\033\013" +
    "\027\034\055\041\052\044\041\045\034\046\062\047\030" +
    "\001\002\000\050\004\156\005\uffe9\010\uffe9\011\uffe9\012" +
    "\uffe9\013\uffe9\014\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9" +
    "\021\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9\026\uffe9\027" +
    "\uffe9\030\uffe9\001\002\000\016\002\ufffd\031\ufffd\032\ufffd" +
    "\036\ufffd\040\ufffd\042\ufffd\001\002\000\052\004\ufff9\006" +
    "\ufff9\007\ufff9\013\ufff9\014\ufff9\015\ufff9\031\ufff9\032\ufff9" +
    "\034\ufff9\035\ufff9\036\ufff9\037\ufff9\040\ufff9\041\ufff9\042" +
    "\ufff9\043\ufff9\044\ufff9\045\ufff9\046\ufff9\047\ufff9\001\002" +
    "\000\026\004\033\013\027\014\026\015\025\034\055\041" +
    "\052\044\041\045\034\046\062\047\030\001\002\000\046" +
    "\005\uffee\010\uffee\011\uffee\012\uffee\013\uffee\014\uffee\015" +
    "\uffee\016\uffee\017\uffee\020\uffee\021\uffee\022\uffee\023\uffee" +
    "\024\uffee\025\uffee\026\uffee\027\uffee\030\uffee\001\002\000" +
    "\032\005\uffd2\010\uffd2\011\uffd2\012\uffd2\021\144\022\143" +
    "\023\142\024\141\025\uffd2\026\uffd2\027\uffd2\030\uffd2\001" +
    "\002\000\022\005\uffc7\010\uffc7\011\uffc7\012\uffc7\025\137" +
    "\026\136\027\uffc7\030\uffc7\001\002\000\016\005\uffc8\010" +
    "\uffc8\011\uffc8\012\uffc8\027\uffc8\030\uffc8\001\002\000\016" +
    "\005\uffc9\010\uffc9\011\uffc9\012\uffc9\027\uffc9\030\uffc9\001" +
    "\002\000\046\005\uffec\010\uffec\011\uffec\012\uffec\013\uffec" +
    "\014\uffec\015\uffec\016\uffec\017\uffec\020\uffec\021\uffec\022" +
    "\uffec\023\uffec\024\uffec\025\uffec\026\uffec\027\uffec\030\uffec" +
    "\001\002\000\016\005\uffd0\010\uffd0\011\uffd0\012\uffd0\027" +
    "\uffd0\030\uffd0\001\002\000\016\005\uffce\010\uffce\011\uffce" +
    "\012\uffce\027\134\030\uffce\001\002\000\014\005\uffcc\010" +
    "\uffcc\011\uffcc\012\131\030\130\001\002\000\010\005\uffca" +
    "\010\uffca\011\uffca\001\002\000\010\005\uffcb\010\uffcb\011" +
    "\uffcb\001\002\000\052\004\ufff8\006\ufff8\007\ufff8\013\ufff8" +
    "\014\ufff8\015\ufff8\031\ufff8\032\ufff8\034\ufff8\035\ufff8\036" +
    "\ufff8\037\ufff8\040\ufff8\041\ufff8\042\ufff8\043\ufff8\044\ufff8" +
    "\045\ufff8\046\ufff8\047\ufff8\001\002\000\004\004\124\001" +
    "\002\000\004\011\123\001\002\000\046\005\uffeb\010\uffeb" +
    "\011\uffeb\012\uffeb\013\uffeb\014\uffeb\015\uffeb\016\uffeb\017" +
    "\uffeb\020\uffeb\021\uffeb\022\uffeb\023\uffeb\024\uffeb\025\uffeb" +
    "\026\uffeb\027\uffeb\030\uffeb\001\002\000\026\004\033\013" +
    "\027\014\026\015\025\034\055\041\052\044\041\045\034" +
    "\046\062\047\030\001\002\000\004\004\113\001\002\000" +
    "\046\005\uffea\010\uffea\011\uffea\012\uffea\013\uffea\014\uffea" +
    "\015\uffea\016\uffea\017\uffea\020\uffea\021\uffea\022\uffea\023" +
    "\uffea\024\uffea\025\uffea\026\uffea\027\uffea\030\uffea\001\002" +
    "\000\046\005\uffe3\010\uffe3\011\uffe3\012\uffe3\013\112\014" +
    "\111\015\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3" +
    "\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\001" +
    "\002\000\004\047\076\001\002\000\042\005\uffe0\010\uffe0" +
    "\011\uffe0\012\uffe0\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021" +
    "\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0" +
    "\030\uffe0\001\002\000\042\005\uffdd\010\uffdd\011\uffdd\012" +
    "\uffdd\015\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd" +
    "\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd\030\uffdd\001" +
    "\002\000\046\005\uffed\010\uffed\011\uffed\012\uffed\013\uffed" +
    "\014\uffed\015\uffed\016\uffed\017\uffed\020\uffed\021\uffed\022" +
    "\uffed\023\uffed\024\uffed\025\uffed\026\uffed\027\uffed\030\uffed" +
    "\001\002\000\042\005\uffda\010\uffda\011\uffda\012\uffda\015" +
    "\uffda\016\071\017\072\020\uffda\021\uffda\022\uffda\023\uffda" +
    "\024\uffda\025\uffda\026\uffda\027\uffda\030\uffda\001\002\000" +
    "\036\005\uffc6\010\uffc6\011\uffc6\012\uffc6\015\066\020\067" +
    "\021\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6\027" +
    "\uffc6\030\uffc6\001\002\000\032\005\uffd5\010\uffd5\011\uffd5" +
    "\012\uffd5\021\uffd5\022\uffd5\023\uffd5\024\uffd5\025\uffd5\026" +
    "\uffd5\027\uffd5\030\uffd5\001\002\000\026\004\033\013\027" +
    "\014\026\015\025\034\055\041\052\044\041\045\034\046" +
    "\062\047\030\001\002\000\026\004\033\013\027\014\026" +
    "\015\025\034\055\041\052\044\041\045\034\046\062\047" +
    "\030\001\002\000\042\005\uffdc\010\uffdc\011\uffdc\012\uffdc" +
    "\015\uffdc\016\071\017\072\020\uffdc\021\uffdc\022\uffdc\023" +
    "\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\030\uffdc\001\002" +
    "\000\026\004\033\013\027\014\026\015\025\034\055\041" +
    "\052\044\041\045\034\046\062\047\030\001\002\000\026" +
    "\004\033\013\027\014\026\015\025\034\055\041\052\044" +
    "\041\045\034\046\062\047\030\001\002\000\042\005\uffde" +
    "\010\uffde\011\uffde\012\uffde\015\uffde\016\uffde\017\uffde\020" +
    "\uffde\021\uffde\022\uffde\023\uffde\024\uffde\025\uffde\026\uffde" +
    "\027\uffde\030\uffde\001\002\000\042\005\uffdf\010\uffdf\011" +
    "\uffdf\012\uffdf\015\uffdf\016\uffdf\017\uffdf\020\uffdf\021\uffdf" +
    "\022\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf\027\uffdf\030" +
    "\uffdf\001\002\000\042\005\uffdb\010\uffdb\011\uffdb\012\uffdb" +
    "\015\uffdb\016\071\017\072\020\uffdb\021\uffdb\022\uffdb\023" +
    "\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb\030\uffdb\001\002" +
    "\000\010\010\077\011\101\012\100\001\002\000\006\011" +
    "\uffbd\047\105\001\002\000\026\004\033\013\027\014\026" +
    "\015\025\034\055\041\052\044\041\045\034\046\062\047" +
    "\030\001\002\000\054\004\ufff5\006\ufff5\007\ufff5\013\ufff5" +
    "\014\ufff5\015\ufff5\031\ufff5\032\ufff5\033\ufff5\034\ufff5\035" +
    "\ufff5\036\ufff5\037\ufff5\040\ufff5\041\ufff5\042\ufff5\043\ufff5" +
    "\044\ufff5\045\ufff5\046\ufff5\047\ufff5\001\002\000\004\011" +
    "\103\001\002\000\054\004\ufff3\006\ufff3\007\ufff3\013\ufff3" +
    "\014\ufff3\015\ufff3\031\ufff3\032\ufff3\033\ufff3\034\ufff3\035" +
    "\ufff3\036\ufff3\037\ufff3\040\ufff3\041\ufff3\042\ufff3\043\ufff3" +
    "\044\ufff3\045\ufff3\046\ufff3\047\ufff3\001\002\000\004\011" +
    "\110\001\002\000\006\010\106\011\uffbc\001\002\000\006" +
    "\011\uffbd\047\105\001\002\000\004\011\uffbb\001\002\000" +
    "\054\004\ufff4\006\ufff4\007\ufff4\013\ufff4\014\ufff4\015\ufff4" +
    "\031\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4\036\ufff4\037" +
    "\ufff4\040\ufff4\041\ufff4\042\ufff4\043\ufff4\044\ufff4\045\ufff4" +
    "\046\ufff4\047\ufff4\001\002\000\042\005\uffe5\010\uffe5\011" +
    "\uffe5\012\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5" +
    "\022\uffe5\023\uffe5\024\uffe5\025\uffe5\026\uffe5\027\uffe5\030" +
    "\uffe5\001\002\000\042\005\uffe6\010\uffe6\011\uffe6\012\uffe6" +
    "\015\uffe6\016\uffe6\017\uffe6\020\uffe6\021\uffe6\022\uffe6\023" +
    "\uffe6\024\uffe6\025\uffe6\026\uffe6\027\uffe6\030\uffe6\001\002" +
    "\000\026\004\033\013\027\014\026\015\025\034\055\041" +
    "\052\044\041\045\034\046\062\047\030\001\002\000\004" +
    "\005\115\001\002\000\050\004\033\006\032\013\027\014" +
    "\026\015\025\031\007\032\006\034\055\035\054\036\014" +
    "\037\053\040\013\041\052\042\012\043\050\044\041\045" +
    "\034\046\062\047\030\001\002\000\004\033\117\001\002" +
    "\000\050\004\033\006\032\013\027\014\026\015\025\031" +
    "\007\032\006\034\055\035\054\036\014\037\053\040\013" +
    "\041\052\042\012\043\050\044\041\045\034\046\062\047" +
    "\030\001\002\000\054\004\uffef\006\uffef\007\uffef\013\uffef" +
    "\014\uffef\015\uffef\031\uffef\032\uffef\033\uffef\034\uffef\035" +
    "\uffef\036\uffef\037\uffef\040\uffef\041\uffef\042\uffef\043\uffef" +
    "\044\uffef\045\uffef\046\uffef\047\uffef\001\002\000\004\011" +
    "\122\001\002\000\054\004\ufff2\006\ufff2\007\ufff2\013\ufff2" +
    "\014\ufff2\015\ufff2\031\ufff2\032\ufff2\033\ufff2\034\ufff2\035" +
    "\ufff2\036\ufff2\037\ufff2\040\ufff2\041\ufff2\042\ufff2\043\ufff2" +
    "\044\ufff2\045\ufff2\046\ufff2\047\ufff2\001\002\000\054\004" +
    "\ufff6\006\ufff6\007\ufff6\013\ufff6\014\ufff6\015\ufff6\031\ufff6" +
    "\032\ufff6\033\ufff6\034\ufff6\035\ufff6\036\ufff6\037\ufff6\040" +
    "\ufff6\041\ufff6\042\ufff6\043\ufff6\044\ufff6\045\ufff6\046\ufff6" +
    "\047\ufff6\001\002\000\026\004\033\013\027\014\026\015" +
    "\025\034\055\041\052\044\041\045\034\046\062\047\030" +
    "\001\002\000\004\005\126\001\002\000\050\004\033\006" +
    "\032\013\027\014\026\015\025\031\007\032\006\034\055" +
    "\035\054\036\014\037\053\040\013\041\052\042\012\043" +
    "\050\044\041\045\034\046\062\047\030\001\002\000\054" +
    "\004\ufff1\006\ufff1\007\ufff1\013\ufff1\014\ufff1\015\ufff1\031" +
    "\ufff1\032\ufff1\033\ufff1\034\ufff1\035\ufff1\036\ufff1\037\ufff1" +
    "\040\ufff1\041\ufff1\042\ufff1\043\ufff1\044\ufff1\045\ufff1\046" +
    "\ufff1\047\ufff1\001\002\000\026\004\033\013\027\014\026" +
    "\015\025\034\055\041\052\044\041\045\034\046\062\047" +
    "\030\001\002\000\026\004\033\013\027\014\026\015\025" +
    "\034\055\041\052\044\041\045\034\046\062\047\030\001" +
    "\002\000\010\005\uffcd\010\uffcd\011\uffcd\001\002\000\016" +
    "\005\uffcf\010\uffcf\011\uffcf\012\uffcf\027\134\030\uffcf\001" +
    "\002\000\026\004\033\013\027\014\026\015\025\034\055" +
    "\041\052\044\041\045\034\046\062\047\030\001\002\000" +
    "\016\005\uffd1\010\uffd1\011\uffd1\012\uffd1\027\uffd1\030\uffd1" +
    "\001\002\000\026\004\033\013\027\014\026\015\025\034" +
    "\055\041\052\044\041\045\034\046\062\047\030\001\002" +
    "\000\026\004\033\013\027\014\026\015\025\034\055\041" +
    "\052\044\041\045\034\046\062\047\030\001\002\000\032" +
    "\005\uffd4\010\uffd4\011\uffd4\012\uffd4\021\144\022\143\023" +
    "\142\024\141\025\uffd4\026\uffd4\027\uffd4\030\uffd4\001\002" +
    "\000\026\004\033\013\027\014\026\015\025\034\055\041" +
    "\052\044\041\045\034\046\062\047\030\001\002\000\026" +
    "\004\033\013\027\014\026\015\025\034\055\041\052\044" +
    "\041\045\034\046\062\047\030\001\002\000\026\004\033" +
    "\013\027\014\026\015\025\034\055\041\052\044\041\045" +
    "\034\046\062\047\030\001\002\000\026\004\033\013\027" +
    "\014\026\015\025\034\055\041\052\044\041\045\034\046" +
    "\062\047\030\001\002\000\032\005\uffd9\010\uffd9\011\uffd9" +
    "\012\uffd9\021\uffd9\022\uffd9\023\uffd9\024\uffd9\025\uffd9\026" +
    "\uffd9\027\uffd9\030\uffd9\001\002\000\032\005\uffd8\010\uffd8" +
    "\011\uffd8\012\uffd8\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025" +
    "\uffd8\026\uffd8\027\uffd8\030\uffd8\001\002\000\032\005\uffd7" +
    "\010\uffd7\011\uffd7\012\uffd7\021\uffd7\022\uffd7\023\uffd7\024" +
    "\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7\001\002\000\032" +
    "\005\uffd6\010\uffd6\011\uffd6\012\uffd6\021\uffd6\022\uffd6\023" +
    "\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030\uffd6\001\002" +
    "\000\032\005\uffd3\010\uffd3\011\uffd3\012\uffd3\021\144\022" +
    "\143\023\142\024\141\025\uffd3\026\uffd3\027\uffd3\030\uffd3" +
    "\001\002\000\004\005\153\001\002\000\046\005\uffe7\010" +
    "\uffe7\011\uffe7\012\uffe7\013\uffe7\014\uffe7\015\uffe7\016\uffe7" +
    "\017\uffe7\020\uffe7\021\uffe7\022\uffe7\023\uffe7\024\uffe7\025" +
    "\uffe7\026\uffe7\027\uffe7\030\uffe7\001\002\000\052\004\033" +
    "\006\032\007\155\013\027\014\026\015\025\031\007\032" +
    "\006\034\055\035\054\036\014\037\053\040\013\041\052" +
    "\042\012\043\050\044\041\045\034\046\062\047\030\001" +
    "\002\000\054\004\ufff0\006\ufff0\007\ufff0\013\ufff0\014\ufff0" +
    "\015\ufff0\031\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0\036" +
    "\ufff0\037\ufff0\040\ufff0\041\ufff0\042\ufff0\043\ufff0\044\ufff0" +
    "\045\ufff0\046\ufff0\047\ufff0\001\002\000\030\004\033\005" +
    "\uffc5\013\027\014\026\015\025\034\055\041\052\044\041" +
    "\045\034\046\062\047\030\001\002\000\004\005\163\001" +
    "\002\000\006\005\uffc4\010\161\001\002\000\030\004\033" +
    "\005\uffc5\013\027\014\026\015\025\034\055\041\052\044" +
    "\041\045\034\046\062\047\030\001\002\000\004\005\uffc3" +
    "\001\002\000\046\005\uffe8\010\uffe8\011\uffe8\012\uffe8\013" +
    "\uffe8\014\uffe8\015\uffe8\016\uffe8\017\uffe8\020\uffe8\021\uffe8" +
    "\022\uffe8\023\uffe8\024\uffe8\025\uffe8\026\uffe8\027\uffe8\030" +
    "\uffe8\001\002\000\042\005\uffe4\010\uffe4\011\uffe4\012\uffe4" +
    "\015\uffe4\016\uffe4\017\uffe4\020\uffe4\021\uffe4\022\uffe4\023" +
    "\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4\030\uffe4\001\002" +
    "\000\042\005\uffe2\010\uffe2\011\uffe2\012\uffe2\015\uffe2\016" +
    "\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2\023\uffe2\024\uffe2" +
    "\025\uffe2\026\uffe2\027\uffe2\030\uffe2\001\002\000\042\005" +
    "\uffe1\010\uffe1\011\uffe1\012\uffe1\015\uffe1\016\uffe1\017\uffe1" +
    "\020\uffe1\021\uffe1\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026" +
    "\uffe1\027\uffe1\030\uffe1\001\002\000\016\005\ufffc\031\007" +
    "\032\006\036\014\040\013\042\012\001\002\000\004\005" +
    "\ufffa\001\002\000\006\005\ufff7\010\ufff7\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\010\032\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\005\020\007\017\032\016\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\023\001\001\000\046\010\046\011" +
    "\055\012\057\013\060\014\062\015\063\016\034\017\035" +
    "\020\042\021\043\022\044\023\050\024\045\025\041\026" +
    "\037\027\036\030\064\032\056\001\001\000\006\011\055" +
    "\012\165\001\001\000\006\011\055\012\164\001\001\000" +
    "\006\011\055\012\163\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\153\001\001\000\042\011\055\012" +
    "\057\013\060\014\062\015\063\016\034\017\035\020\042" +
    "\021\043\022\044\023\151\024\045\025\041\026\037\027" +
    "\036\030\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\042\011\055\012\057\013\060\014\062\015\063\016" +
    "\034\017\035\020\042\021\043\022\044\023\120\024\045" +
    "\025\041\026\037\027\036\030\064\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\011\055\012\057\013\060\014\074\001\001\000\012\011" +
    "\055\012\057\013\060\014\067\001\001\000\002\001\001" +
    "\000\010\011\055\012\057\013\073\001\001\000\010\011" +
    "\055\012\057\013\072\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\033" +
    "\103\001\001\000\042\011\055\012\057\013\060\014\062" +
    "\015\063\016\034\017\035\020\042\021\043\022\044\023" +
    "\101\024\045\025\041\026\037\027\036\030\064\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\033\106\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\042\011\055\012\057\013\060\014\062" +
    "\015\063\016\034\017\035\020\042\021\043\022\044\023" +
    "\113\024\045\025\041\026\037\027\036\030\064\001\001" +
    "\000\002\001\001\000\046\010\115\011\055\012\057\013" +
    "\060\014\062\015\063\016\034\017\035\020\042\021\043" +
    "\022\044\023\050\024\045\025\041\026\037\027\036\030" +
    "\064\032\056\001\001\000\002\001\001\000\046\010\117" +
    "\011\055\012\057\013\060\014\062\015\063\016\034\017" +
    "\035\020\042\021\043\022\044\023\050\024\045\025\041" +
    "\026\037\027\036\030\064\032\056\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\042\011\055\012\057\013\060\014\062\015\063\016" +
    "\034\017\035\020\042\021\043\022\044\023\124\024\045" +
    "\025\041\026\037\027\036\030\064\001\001\000\002\001" +
    "\001\000\046\010\126\011\055\012\057\013\060\014\062" +
    "\015\063\016\034\017\035\020\042\021\043\022\044\023" +
    "\050\024\045\025\041\026\037\027\036\030\064\032\056" +
    "\001\001\000\002\001\001\000\032\011\055\012\057\013" +
    "\060\014\062\015\063\016\034\017\035\020\132\025\041" +
    "\026\037\027\036\030\064\001\001\000\036\011\055\012" +
    "\057\013\060\014\062\015\063\016\034\017\035\020\042" +
    "\021\043\022\131\025\041\026\037\027\036\030\064\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\011\055" +
    "\012\057\013\060\014\062\015\063\016\034\017\035\025" +
    "\134\026\037\027\036\030\064\001\001\000\002\001\001" +
    "\000\020\011\055\012\057\013\060\014\062\015\063\016" +
    "\150\030\064\001\001\000\020\011\055\012\057\013\060" +
    "\014\062\015\063\016\137\030\064\001\001\000\002\001" +
    "\001\000\016\011\055\012\057\013\060\014\062\015\063" +
    "\030\147\001\001\000\016\011\055\012\057\013\060\014" +
    "\062\015\063\030\146\001\001\000\016\011\055\012\057" +
    "\013\060\014\062\015\063\030\145\001\001\000\016\011" +
    "\055\012\057\013\060\014\062\015\063\030\144\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\046\010\046\011\055\012\057\013\060\014" +
    "\062\015\063\016\034\017\035\020\042\021\043\022\044" +
    "\023\050\024\045\025\041\026\037\027\036\030\064\032" +
    "\056\001\001\000\002\001\001\000\044\011\055\012\057" +
    "\013\060\014\062\015\063\016\034\017\035\020\042\021" +
    "\043\022\044\023\157\024\045\025\041\026\037\027\036" +
    "\030\064\031\156\001\001\000\002\001\001\000\002\001" +
    "\001\000\044\011\055\012\057\013\060\014\062\015\063" +
    "\016\034\017\035\020\042\021\043\022\044\023\157\024" +
    "\045\025\041\026\037\027\036\030\064\031\161\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\005\167\007\017" +
    "\032\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  public Clike.Absyn.Program pProgram() throws Exception
  {
    java_cup.runtime.Symbol res = parse();
    return (Clike.Absyn.Program) res.value;
  }

public <B,A extends java.util.LinkedList<? super B>> A cons_(B x, A xs) { xs.addFirst(x); return xs; }

public void syntax_error(java_cup.runtime.Symbol cur_token)
{
  report_error("Syntax Error, trying to recover and continue parse...", cur_token);
}

public void unrecovered_syntax_error(java_cup.runtime.Symbol cur_token) throws java.lang.Exception
{
  throw new Exception("Unrecoverable Syntax Error");
}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


public java_cup.runtime.ComplexSymbolFactory.Location getLeftLocation(
    java_cup.runtime.ComplexSymbolFactory.Location ... locations) {
  for (java_cup.runtime.ComplexSymbolFactory.Location l : locations) {
    if (l != null) {
      return l;
    }
  }
  return null;
}

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT =null;
		Clike.Absyn.Program start_val = (Clike.Absyn.Program)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= ListDef 
            {
              Clike.Absyn.Program RESULT =null;
		Clike.Absyn.ListDef p_1 = (Clike.Absyn.ListDef)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.PDefs(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Program",0, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ListDef ::= 
            {
              Clike.Absyn.ListDef RESULT =null;
		 RESULT = new Clike.Absyn.ListDef(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListDef",1, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ListDef ::= ListDef Def 
            {
              Clike.Absyn.ListDef RESULT =null;
		Clike.Absyn.ListDef p_1 = (Clike.Absyn.ListDef)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Def p_2 = (Clike.Absyn.Def)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; p_1.addLast(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListDef",1, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Def ::= Type Id _SYMB_0 ListArg _SYMB_1 _SYMB_2 ListStm _SYMB_3 
            {
              Clike.Absyn.Def RESULT =null;
		Clike.Absyn.Type p_1 = (Clike.Absyn.Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		String p_2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		Clike.Absyn.ListArg p_4 = (Clike.Absyn.ListArg)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		Object p_5 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		Object p_6 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.ListStm p_7 = (Clike.Absyn.ListStm)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_8 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.DFun(p_1,p_2,p_4,p_7); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Def",2, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // ListArg ::= 
            {
              Clike.Absyn.ListArg RESULT =null;
		 RESULT = new Clike.Absyn.ListArg(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListArg",3, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ListArg ::= Arg 
            {
              Clike.Absyn.ListArg RESULT =null;
		Clike.Absyn.Arg p_1 = (Clike.Absyn.Arg)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ListArg(); RESULT.addLast(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListArg",3, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ListArg ::= Arg _SYMB_4 ListArg 
            {
              Clike.Absyn.ListArg RESULT =null;
		Clike.Absyn.Arg p_1 = (Clike.Absyn.Arg)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.ListArg p_3 = (Clike.Absyn.ListArg)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_3; p_3.addFirst(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListArg",3, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ListStm ::= 
            {
              Clike.Absyn.ListStm RESULT =null;
		 RESULT = new Clike.Absyn.ListStm(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListStm",4, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ListStm ::= ListStm Stm 
            {
              Clike.Absyn.ListStm RESULT =null;
		Clike.Absyn.ListStm p_1 = (Clike.Absyn.ListStm)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Stm p_2 = (Clike.Absyn.Stm)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; p_1.addLast(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListStm",4, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Arg ::= Type Id 
            {
              Clike.Absyn.Arg RESULT =null;
		Clike.Absyn.Type p_1 = (Clike.Absyn.Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		String p_2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ADecl(p_1,p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Arg",5, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Stm ::= Exp _SYMB_5 
            {
              Clike.Absyn.Stm RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SExp(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Stm ::= Type Id _SYMB_5 
            {
              Clike.Absyn.Stm RESULT =null;
		Clike.Absyn.Type p_1 = (Clike.Absyn.Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		String p_2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SDecl(p_1,p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Stm ::= Type Id _SYMB_4 ListId _SYMB_5 
            {
              Clike.Absyn.Stm RESULT =null;
		Clike.Absyn.Type p_1 = (Clike.Absyn.Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		String p_2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.ListId p_4 = (Clike.Absyn.ListId)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_5 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SDecls(p_1,p_2,p_4); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Stm ::= Type Id _SYMB_6 Exp _SYMB_5 
            {
              Clike.Absyn.Stm RESULT =null;
		Clike.Absyn.Type p_1 = (Clike.Absyn.Type)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		String p_2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.Exp p_4 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_5 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SInit(p_1,p_2,p_4); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Stm ::= _SYMB_27 Exp _SYMB_5 
            {
              Clike.Absyn.Stm RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.Exp p_2 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SReturn(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Stm ::= _SYMB_31 _SYMB_0 Exp _SYMB_1 Stm 
            {
              Clike.Absyn.Stm RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_4 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Stm p_5 = (Clike.Absyn.Stm)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SWhile(p_3,p_5); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Stm ::= _SYMB_2 ListStm _SYMB_3 
            {
              Clike.Absyn.Stm RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.ListStm p_2 = (Clike.Absyn.ListStm)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SBlock(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Stm ::= _SYMB_25 _SYMB_0 Exp _SYMB_1 Stm _SYMB_23 Stm 
            {
              Clike.Absyn.Stm RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		Object p_4 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		Clike.Absyn.Stm p_5 = (Clike.Absyn.Stm)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_6 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Stm p_7 = (Clike.Absyn.Stm)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.SIfElse(p_3,p_5,p_7); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stm",6, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Exp15 ::= _INTEGER_ 
            {
              Clike.Absyn.Exp RESULT =null;
		Integer p_1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EInt(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Exp15 ::= _DOUBLE_ 
            {
              Clike.Absyn.Exp RESULT =null;
		Double p_1 = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EDouble(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Exp15 ::= _STRING_ 
            {
              Clike.Absyn.Exp RESULT =null;
		String p_1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EString(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Exp15 ::= _SYMB_29 
            {
              Clike.Absyn.Exp RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ETrue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Exp15 ::= _SYMB_24 
            {
              Clike.Absyn.Exp RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EFalse(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Exp15 ::= Id 
            {
              Clike.Absyn.Exp RESULT =null;
		String p_1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EId(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Exp15 ::= Id _SYMB_0 ListExp _SYMB_1 
            {
              Clike.Absyn.Exp RESULT =null;
		String p_1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.ListExp p_3 = (Clike.Absyn.ListExp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_4 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ECall(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Exp15 ::= _SYMB_0 Exp _SYMB_1 
            {
              Clike.Absyn.Exp RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Clike.Absyn.Exp p_2 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp15",7, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Exp14 ::= Exp15 _SYMB_7 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EPIncr(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp14",8, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Exp14 ::= Exp15 _SYMB_8 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EPDecr(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp14",8, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Exp14 ::= _SYMB_7 Exp14 
            {
              Clike.Absyn.Exp RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_2 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EIncr(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp14",8, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Exp14 ::= Exp15 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp14",8, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Exp13 ::= _SYMB_8 Exp14 
            {
              Clike.Absyn.Exp RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_2 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EDecr(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp13",9, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Exp13 ::= _SYMB_9 Exp14 
            {
              Clike.Absyn.Exp RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_2 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ENeg(p_2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp13",9, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Exp13 ::= Exp14 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp13",9, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Exp12 ::= Exp12 _SYMB_10 Exp13 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EMul(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp12",10, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Exp12 ::= Exp12 _SYMB_11 Exp13 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EDiv(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp12",10, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Exp12 ::= Exp13 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp12",10, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Exp11 ::= Exp11 _SYMB_12 Exp12 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EAdd(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp11",11, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Exp11 ::= Exp11 _SYMB_9 Exp12 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ESub(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp11",11, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Exp11 ::= Exp12 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp11",11, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Exp9 ::= Exp9 _SYMB_13 Exp10 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ELt(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp9",12, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Exp9 ::= Exp9 _SYMB_14 Exp10 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EGt(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp9",12, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Exp9 ::= Exp9 _SYMB_15 Exp10 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ELEq(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp9",12, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Exp9 ::= Exp9 _SYMB_16 Exp10 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EGEq(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp9",12, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Exp9 ::= Exp10 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp9",12, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Exp8 ::= Exp8 _SYMB_17 Exp9 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EEq(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp8",13, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Exp8 ::= Exp8 _SYMB_18 Exp9 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ENEq(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp8",13, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Exp8 ::= Exp9 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp8",13, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Exp4 ::= Exp4 _SYMB_19 Exp5 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EAnd(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp4",14, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Exp4 ::= Exp5 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp4",14, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Exp3 ::= Exp3 _SYMB_20 Exp4 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EOr(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp3",15, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Exp3 ::= Exp4 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp3",15, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // Exp2 ::= Exp3 _SYMB_6 Exp2 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.Exp p_3 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.EAss(p_1,p_3); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp2",16, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // Exp2 ::= Exp3 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp2",16, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Exp ::= Exp1 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp",17, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Exp1 ::= Exp2 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp1",18, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Exp5 ::= Exp6 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp5",19, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Exp6 ::= Exp7 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp6",20, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Exp7 ::= Exp8 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp7",21, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Exp10 ::= Exp11 
            {
              Clike.Absyn.Exp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exp10",22, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // ListExp ::= 
            {
              Clike.Absyn.ListExp RESULT =null;
		 RESULT = new Clike.Absyn.ListExp(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListExp",23, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // ListExp ::= Exp 
            {
              Clike.Absyn.ListExp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ListExp(); RESULT.addLast(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListExp",23, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // ListExp ::= Exp _SYMB_4 ListExp 
            {
              Clike.Absyn.ListExp RESULT =null;
		Clike.Absyn.Exp p_1 = (Clike.Absyn.Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.ListExp p_3 = (Clike.Absyn.ListExp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_3; p_3.addFirst(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListExp",23, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Type ::= _SYMB_21 
            {
              Clike.Absyn.Type RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.Tbool(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",24, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Type ::= _SYMB_22 
            {
              Clike.Absyn.Type RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.Tdouble(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",24, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // Type ::= _SYMB_26 
            {
              Clike.Absyn.Type RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.Tint(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",24, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // Type ::= _SYMB_28 
            {
              Clike.Absyn.Type RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.Tstring(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",24, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // Type ::= _SYMB_30 
            {
              Clike.Absyn.Type RESULT =null;
		Object p_1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.Tvoid(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",24, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // ListId ::= 
            {
              Clike.Absyn.ListId RESULT =null;
		 RESULT = new Clike.Absyn.ListId(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListId",25, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // ListId ::= Id 
            {
              Clike.Absyn.ListId RESULT =null;
		String p_1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Clike.Absyn.ListId(); RESULT.addLast(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListId",25, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // ListId ::= Id _SYMB_4 ListId 
            {
              Clike.Absyn.ListId RESULT =null;
		String p_1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		Object p_2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		Clike.Absyn.ListId p_3 = (Clike.Absyn.ListId)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p_3; p_3.addFirst(p_1); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListId",25, RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
